name = "SmallCollections"
uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
authors = ["matthias314"]
version = "0.5.2-DEV"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
BangBangExt = "BangBang"
StaticArraysExt = "StaticArrays"

[compat]
BangBang = "0.4"
BitIntegers = "0.3"
CpuId = "0.3"
LinearAlgebra = "1"
StaticArrays = "1.5"
julia = "1.10"
